language: node_js
node_js:
  - '8'
  - '10'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: S9GPKBrVMGpsw6t+wEA5aGaY759zvnoAZPPGwAIJmkh5ToRo3HWg6temcE4lckQI7ZB5GyOpFl06L3cbq4Sw8RC2L/cioyfQhgt946/hj1Ip3MTsFd/BrXS6G7Z5FMOPS1kAoCV4Wp9v0u4x5N59wOLvwampQa2bi95uGG4oHrVmEfkmkabyET6mwdpTrJ3aKADSAfwJaBqraYHYpyaMAfwaFOrbRc9m81iGWlqDw0eLN+bjbJe79hMDll5T3IOyObdatIMq+SbWP+pMU+994JHDMZzQM4KYtU2qWkCOaeBgzBrDOGOT9zWycHsCxwxBpyAS8upLx8Zf6DdjmJAqXddlufwXkb9YM3799J3le7nzjOGFV4wBsY6XdyM34Ar6ys/vVtinmRXvjmye5ooxlpgj3LACStTdYr38Jz2olpCK9YlsCDfGZPgTqaPqCF9y1oLrncP7xh2WSvrC4HSz8t3DohzWoFHFJakMYcJ9xm0uWrVvEX2nC74cRAh815h/x2UYnKukAborlx2e1PqfE/+i+X4pL9uOEIXT0G/iaT9wNl1i3Sl955KvCFKKuhlwp7ACJNvpaNMyrwN1iiyL/2C7rZa7dlL/iuVe6qfB3TgaYhl7xglG+cfuvHrfHY6tLK6MAHngd0D2Bj03RTAVN4VUnnbF23If++5b+cUlOOs=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-okta
    node: '8'
